"""modelo completo final

Revision ID: 52d792e12ce3
Revises: 
Create Date: 2026-04-01 02:47:19.135777

"""
import pgvector
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52d792e12ce3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pacientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre_enc', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.String(), nullable=True),
    sa.Column('diagnostico', sa.String(), nullable=True),
    sa.Column('nivel_soporte', sa.Integer(), nullable=True),
    sa.Column('observaciones_enc', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parentescos',
    sa.Column('id_parentesco', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_parentesco')
    )
    op.create_table('provincias',
    sa.Column('id_provincia', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_provincia')
    )
    op.create_table('equipos_terapeuticos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localidades',
    sa.Column('codigo_postal', sa.String(length=4), nullable=False),
    sa.Column('sub_codigo_postal', sa.String(length=2), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('id_provincia', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['id_provincia'], ['provincias.id_provincia'], ),
    sa.PrimaryKeyConstraint('codigo_postal', 'sub_codigo_postal')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('domicilio', sa.String(), nullable=True),
    sa.Column('codigo_postal', sa.String(length=4), nullable=True),
    sa.Column('sub_codigo_postal', sa.String(length=2), nullable=True),
    sa.Column('rol', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('email_verificado', sa.Boolean(), nullable=True),
    sa.Column('intentos_fallidos', sa.Integer(), nullable=True),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('bloqueado_hasta', sa.DateTime(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('actualizado_en', sa.DateTime(), nullable=True),
    sa.Column('ultimo_acceso', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['codigo_postal', 'sub_codigo_postal'], ['localidades.codigo_postal', 'localidades.sub_codigo_postal'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_usuario_localidad', 'usuarios', ['codigo_postal', 'sub_codigo_postal'], unique=False)
    op.create_index(op.f('ix_usuarios_creado_en'), 'usuarios', ['creado_en'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_rol'), 'usuarios', ['rol'], unique=False)
    op.create_table('administradores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('nivel_acceso', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('accion', sa.String(), nullable=True),
    sa.Column('recurso_tipo', sa.String(), nullable=True),
    sa.Column('recurso_id', sa.UUID(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('resultado', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('consentimientos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('aceptado', sa.Boolean(), nullable=True),
    sa.Column('ip_origen', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('revocado', sa.Boolean(), nullable=True),
    sa.Column('aceptado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('familiares',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('contacto_emergencia', sa.Boolean(), nullable=True),
    sa.Column('consentimiento_en', sa.DateTime(), nullable=True),
    sa.Column('consentimiento_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recursos_profesionales',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subido_por', sa.UUID(), nullable=True),
    sa.Column('validado_por', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('url_storage', sa.String(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('embedding_1536', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('subido_en', sa.DateTime(), nullable=True),
    sa.Column('validado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subido_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['validado_por'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_seguimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('autor_id', sa.UUID(), nullable=True),
    sa.Column('contenido_enc', sa.Text(), nullable=True),
    sa.Column('visibilidad', sa.String(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.Date(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.Column('modificado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['autor_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terapeutas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('matricula', sa.String(), nullable=True),
    sa.Column('profesion', sa.String(), nullable=True),
    sa.Column('especialidad', sa.String(), nullable=True),
    sa.Column('institucion', sa.String(), nullable=True),
    sa.Column('tipo_acceso', sa.String(), nullable=True),
    sa.Column('validado', sa.Boolean(), nullable=True),
    sa.Column('institucional', sa.Boolean(), nullable=True),
    sa.Column('validado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('matricula')
    )
    op.create_table('actividades_familiar',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('terapeuta_id', sa.UUID(), nullable=True),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('frecuencia', sa.String(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['terapeuta_id'], ['terapeutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('miembros_equipo',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('equipo_id', sa.UUID(), nullable=True),
    sa.Column('terapeuta_id', sa.UUID(), nullable=True),
    sa.Column('rol_en_equipo', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('asignado_en', sa.DateTime(), nullable=True),
    sa.Column('hasta', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_id'], ['equipos_terapeuticos.id'], ),
    sa.ForeignKeyConstraint(['terapeuta_id'], ['terapeutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permisos_seguimiento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('registro_id', sa.UUID(), nullable=True),
    sa.Column('terapeuta_id', sa.UUID(), nullable=True),
    sa.Column('puede_ver', sa.Boolean(), nullable=True),
    sa.Column('puede_editar', sa.Boolean(), nullable=True),
    sa.Column('puede_eliminar', sa.Boolean(), nullable=True),
    sa.Column('otorgado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['registro_id'], ['registros_seguimiento.id'], ),
    sa.ForeignKeyConstraint(['terapeuta_id'], ['terapeutas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sesiones_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('familiar_id', sa.UUID(), nullable=True),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('contexto_anonimo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iniciada_en', sa.DateTime(), nullable=True),
    sa.Column('cerrada_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familiar_id'], ['familiares.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vinculos_paciente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('familiar_id', sa.UUID(), nullable=True),
    sa.Column('paciente_id', sa.UUID(), nullable=True),
    sa.Column('id_parentesco', sa.String(length=2), nullable=True),
    sa.Column('es_tutor_legal', sa.Boolean(), nullable=True),
    sa.Column('autorizado_medico', sa.Boolean(), nullable=True),
    sa.Column('desde', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['familiar_id'], ['familiares.id'], ),
    sa.ForeignKeyConstraint(['id_parentesco'], ['parentescos.id_parentesco'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mensajes_ia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('emisor', sa.String(), nullable=True),
    sa.Column('genera_alerta', sa.Boolean(), nullable=True),
    sa.Column('enviado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_ia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('progreso_actividad',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actividad_id', sa.UUID(), nullable=True),
    sa.Column('familiar_id', sa.UUID(), nullable=True),
    sa.Column('completada_en', sa.DateTime(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('multimedia', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('nivel_satisfaccion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actividad_id'], ['actividades_familiar.id'], ),
    sa.ForeignKeyConstraint(['familiar_id'], ['familiares.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alertas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sesion_id', sa.UUID(), nullable=True),
    sa.Column('mensaje_id', sa.UUID(), nullable=True),
    sa.Column('revisada_por', sa.UUID(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('severidad', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('resuelta', sa.Boolean(), nullable=True),
    sa.Column('nota_resolucion', sa.Text(), nullable=True),
    sa.Column('creada_en', sa.DateTime(), nullable=True),
    sa.Column('resuelta_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mensaje_id'], ['mensajes_ia.id'], ),
    sa.ForeignKeyConstraint(['revisada_por'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['sesion_id'], ['sesiones_ia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alertas')
    op.drop_table('progreso_actividad')
    op.drop_table('mensajes_ia')
    op.drop_table('vinculos_paciente')
    op.drop_table('sesiones_ia')
    op.drop_table('permisos_seguimiento')
    op.drop_table('miembros_equipo')
    op.drop_table('actividades_familiar')
    op.drop_table('terapeutas')
    op.drop_table('registros_seguimiento')
    op.drop_table('recursos_profesionales')
    op.drop_table('familiares')
    op.drop_table('consentimientos')
    op.drop_table('auditoria')
    op.drop_table('administradores')
    op.drop_index(op.f('ix_usuarios_rol'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_creado_en'), table_name='usuarios')
    op.drop_index('idx_usuario_localidad', table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('localidades')
    op.drop_table('equipos_terapeuticos')
    op.drop_table('provincias')
    op.drop_table('parentescos')
    op.drop_table('pacientes')
    # ### end Alembic commands ###
